### ISSUE TITLE
Huge download size (more than 11 MB)

### ISSUE THREAD

**Issue by ysmoradi** [f4n0/BlazorGenerator#73]
![image](https://github.com/f4n0/BlazorGenerator/assets/5352980/9c26d970-68f7-457d-81e4-b3b639c71620)
It doesn't make any sense!
You can compare it with https://todo.bitplatform.dev and other optimized blazor webassembly websites
![image](https://github.com/f4n0/BlazorGenerator/assets/5352980/343efa5d-2818-4476-b3ad-8cfdc8251a50)

**Comment by f4n0** [comment]
I think i need more context, which page are you loading to see this stats? 
I've looked into the sample app and I'm never exceeding 1.9MB!

**Comment by f4n0** [comment]
I see, this is how the Demo App is published. 
The problem here consists in how the Trimmer is configured. 
I had some problems with the icons when publishing the demo with GitHub Pages (as they are not designed for WebAssembly hosting) and so to make the demo working in GH Pages I had to disable trimming for the Icons. 

Here's a screenshot for an app I'm currently building 
![image](https://github.com/f4n0/BlazorGenerator/assets/36199751/4cd20c60-735c-45f9-98f3-d150e7cf4ecc)

And here the "Server" project in this repo:
![image](https://github.com/f4n0/BlazorGenerator/assets/36199751/a0f63595-b419-40ba-88d8-dc112b192276)


as you see, no performance issue!

**Comment by ysmoradi** [comment]
I can't understand what you're talking about, but I'm closing the issue as it seems there's no issue in your opinion.
